make_data:
  data_file_path: "C:/Users/zach_/Nobackupfile/Data/BDS"     # raw data file dir
  regdata_origin_path: "Regdata/regdata_4_0_industries.csv"
  regdata_doc_path: "Regdata/regdata_4_0_documents.csv"
  regdata_ind_path: "Regdata/regdata_4_0_documents_2digit_naics.csv"
  bds_naics_4_path: "bds2019_naics_4_age.csv"
  bds_sector_size: "bds2019_sector_size_age.csv"
  gdp_path: "BEA/gdp.csv"
  cleaned_data_path: "data/cleaned"
  dep_var: ["job_creation_rate", "net_job_creation_rate", "job_destruction_rate", "estabs_exit_rate", "net_job_creation", "estabs_entry_rate", "reallocation_rate"]
  

model:
  sector_panel: "data/cleaned/sector_panel.h5"
  sector_age_panel: "data/cleaned/sector_age_panel.h5"
  sector_size_panel: "data/cleaned/sector_size_panel.h5"
  sector_age_size_panel: "data/cleaned/sector_age_size_panel.h5"
  results_tables_path: "results/tables"
  results_figs_path: "results/figs"
  dep_var: ["log_emp", "log_avg_emp", "job_creation_rate", "job_destruction_rate", "net_job_creation_rate", "reallocation_rate", "death_rate", "L_0_entry_rate", "estabs_exit_rate", "estabs_entry_rate"]
  error_type: "clustered"
